//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricWeather
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Summary { get; set; }
        public string Icon { get; set; }
        public string PrecipType { get; set; }
        public decimal PrecipIntensity { get; set; }
        public decimal PrecipProbability { get; set; }
        public decimal TemperatureHigh { get; set; }
        public decimal TemperatureLow { get; set; }
        public decimal Humidity { get; set; }
        public decimal CloudCover { get; set; }
        public int AirportId { get; set; }
        public decimal WindSpeed { get; set; }
    
        public virtual Airport Airport { get; set; }
    }
}
