//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public string FlightNumber { get; set; }
        public int FromAirportId { get; set; }
        public int ToAirportId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public int AirlineId { get; set; }
        public Nullable<int> StopNumber { get; set; }
        public int TripId { get; set; }
        public int FlightTypeId { get; set; }
        public int Duration { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        public virtual Category Category { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
