//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchTripWish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchTripWish()
        {
            this.SearchTrips = new HashSet<SearchTrip>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FromAirportId { get; set; }
        public Nullable<int> ToAirportId { get; set; }
        public System.DateTime FromDateMin { get; set; }
        public System.DateTime FromDateMax { get; set; }
        public Nullable<System.DateTime> ToDateMin { get; set; }
        public Nullable<System.DateTime> ToDateMax { get; set; }
        public int DurationMin { get; set; }
        public int DurationMax { get; set; }
        public Nullable<int> FromCityId { get; set; }
        public Nullable<int> ToCityId { get; set; }
        public int MaxStopNumber { get; set; }
        public Nullable<int> CreationUserId { get; set; }
        public Nullable<int> WishedPriceCurrencyId { get; set; }
        public Nullable<decimal> WishedPrice { get; set; }
        public Nullable<decimal> EuroWishedPrice { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchTrip> SearchTrips { get; set; }
        public virtual User User { get; set; }
    }
}
